### ISSUE TITLE
Improve 'ccfy' by adding double c's for words ending with c

### ISSUE THREAD

**Issue by Kaioru** [Kaioru/memefy#1]
Words that end with 'c' should have double c's as well.

For example:
`aesthetic => aethethicc`

**Comment by oat9002** [comment]
Please check if I'm not wrong.

**Comment by Kaioru** [comment]
Hello thanks for the submission. 

This does fulfil the issue requirements of transforming `'aesthetic' => 'aesthethicc'`. 

However, it produces the wrong output `'aesthetic' => 'aesthetic aestheticc'`

Maybe you could add a condition where if the word ends with a 'c', pad an extra 'c'. Else, run the current code.
