### ISSUE TITLE
Change 'alternating' and 'alternating2' to skip spaces

### ISSUE THREAD

**Issue by Kaioru** [Kaioru/memefy#2]
Currently 'alternating' and 'alternating2' doesn't skip spaces which creates scenarios like these:
`'p i n e apple' => 'p i n e aPpLe'`

Where it should be like this:
`'p i n e apple' => 'p I n E aPpLe'`

One way of implementing this is to change 'alternating' and 'alternating2' to transformers instead of maps currently.

**Comment by lopno** [comment]
I am going to do this.
